# Generated by Django 4.1.1 on 2022-09-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_break_break_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='break',
            name='break_date',
        ),
    ]
