# Generated by Django 4.1.1 on 2022-09-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_break_break_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='current_break',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('AL', 'Picie alkoholu'), ('AT', 'Sprawność i tężyzna fizyczna'), ('M', 'Silna psycha'), ('DR', 'Osiągnięcia związane z innymi używkami'), ('G', 'Ośmieszanie się'), ('DE', 'Niszczenie'), ('O', 'Wszystko inne')], max_length=50),
        ),
    ]
