# Generated by Django 4.1.1 on 2022-09-25 07:41

from django.db import migrations
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_break_current_break'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='current_break',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=False, on=('record',)),
        ),
    ]
