# Generated by Django 4.1.1 on 2022-09-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_break_current_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
