# Generated by Django 4.1.1 on 2022-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_record_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
