# Generated by Django 4.1.1 on 2022-09-25 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_record_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='break_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
