# Generated by Django 4.1.1 on 2022-09-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exclusivebooleanfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0010_alter_break_break_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='breaker_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='break',
            name='current_break',
            field=exclusivebooleanfield.fields.ExclusiveBooleanField(default=True, on=('record',)),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('AL', 'Picie alkoholu'), ('AT', 'Sprawność i tężyzna fizyczna'), ('M', 'Silna psycha'), ('DR', 'Osiągnięcia związane z innymi używkami'), ('G', 'Ośmieszanie się'), ('DE', 'Niszczenie'), ('DA', 'Uszkodzenia ciała, urazy'), ('O', 'Wszystko inne')], max_length=50),
        ),
    ]
