# Generated by Django 4.1.1 on 2022-09-26 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0011_alter_break_breaker_login_alter_break_current_break_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='break_place',
            field=models.CharField(blank=True, default='Brzeg', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='break',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='break',
            name='breaker_login',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
