# Generated by Django 4.1.1 on 2022-09-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_break_break_place_break_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='break',
            old_name='description',
            new_name='break_description',
        ),
        migrations.AddField(
            model_name='break',
            name='break_evidence',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
